=== actiontech/dble/src/main/resources/db.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

        <!--
         -
         - Licensed under the Apache License, Version 2.0 (the "License");
         - you may not use this file except in compliance with the License.
         - You may obtain a copy of the License at
         -
         -      http://www.apache.org/licenses/LICENSE-2.0
         -
         - Unless required by applicable law or agreed to in writing, software
         - distributed under the License is distributed on an "AS IS" BASIS,
         - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         - See the License for the specific language governing permissions and
         - limitations under the License.
        -->
        <!ELEMENT dble:db (dbGroup*)>
        <!ATTLIST dble:db xmlns:dble CDATA #FIXED "http://dble.cloud/">
        <!ATTLIST dble:db version CDATA #IMPLIED>
        <!ELEMENT dbGroup (heartbeat,(dbInstance+))>
        <!ATTLIST dbGroup
                rwSplitMode NMTOKEN #REQUIRED
                name NMTOKEN #REQUIRED
                delayThreshold NMTOKEN #IMPLIED
                disableHA NMTOKEN #IMPLIED>

        <!ELEMENT dbInstance (property*)>
        <!ATTLIST dbInstance
                url CDATA #REQUIRED
                name NMTOKEN #REQUIRED
                password CDATA #REQUIRED
                user CDATA #REQUIRED
                maxCon NMTOKEN #REQUIRED
                minCon NMTOKEN #REQUIRED
                primary NMTOKEN #IMPLIED
                readWeight NMTOKEN #IMPLIED
                id CDATA #IMPLIED
                usingDecrypt NMTOKEN #IMPLIED
                disabled NMTOKEN #IMPLIED>

        <!ELEMENT heartbeat (#PCDATA)>
        <!ATTLIST heartbeat errorRetryCount NMTOKEN #IMPLIED>
        <!ATTLIST heartbeat timeout NMTOKEN #IMPLIED>

        <!ELEMENT property (#PCDATA)*>
        <!ATTLIST property name NMTOKEN #REQUIRED>

=== actiontech/dble/docker-images/obsharding_d-image/mgr/db.xml
<?xml version="1.0"?>
<!--
  ~ Copyright (C) 2016-2023 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->
<!DOCTYPE OBsharding-D:db SYSTEM "db.dtd">
<OBsharding-D:db xmlns:OBsharding-D="http://OBsharding-D.cloud/" version="4.0">
    <dbGroup name="dbGroup1" rwSplitMode="2" delayThreshold="100">
        <heartbeat>select 1</heartbeat>
        <dbInstance name="instanceM1" url="172.18.0.2:3306" user="root" password="123456" maxCon="300" minCon="10"
                    primary="true" readWeight="1" id="xx1">
        </dbInstance>
        <dbInstance name="instanceS1" url="172.18.0.3:3306" user="root" password="123456" maxCon="1000" minCon="10"
                    readWeight="2">
            <property name="testWhileIdle">false</property>
        </dbInstance>
        <dbInstance name="instanceS2" url="172.18.0.4:3306" user="root" password="123456" maxCon="1000" minCon="10"
                    readWeight="2">
            <property name="testWhileIdle">false</property>
        </dbInstance>
    </dbGroup>

    <dbGroup name="dbGroup2" rwSplitMode="0" delayThreshold="100" disableHA="true">
        <heartbeat errorRetryCount="1" timeout="10">select 1</heartbeat>
        <dbInstance name="instanceM2" url="172.18.0.5:3306" user="root" password="123456" maxCon="300" minCon="10"
                    primary="true">
        </dbInstance>
        <dbInstance name="instanceS3" url="172.18.0.6:3306" user="root" password="123456" maxCon="1000" minCon="10"
                    readWeight="2">
            <property name="testWhileIdle">false</property>
        </dbInstance>
        <dbInstance name="instanceS4" url="172.18.0.7:3306" user="root" password="123456" maxCon="1000" minCon="10"
                    readWeight="2">
            <property name="testWhileIdle">false</property>
        </dbInstance>
    </dbGroup>
</OBsharding-D:db>

=== actiontech/dble/docker-images/quick-start/db.xml
<?xml version="1.0"?>
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!DOCTYPE dble:db SYSTEM "db.dtd">
<dble:db xmlns:dble="http://dble.cloud/" version="4.0">
    <dbGroup name="dbGroup1" rwSplitMode="2" delayThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <dbInstance name="instanceM1" url="172.18.0.2:3306" user="root" password="123456" maxCon="300" minCon="10"
                    primary="true" readWeight="1" id="xx1">
        </dbInstance>
        <dbInstance name="instanceS1" url="172.18.0.3:3306" user="root" password="123456" maxCon="1000" minCon="10" readWeight="2">
            <property name="testOnCreate">false</property>
        </dbInstance>
        <dbInstance name="instanceS2" url="172.18.0.4:3306" user="root" password="123456" maxCon="1000" minCon="10" readWeight="2">
            <property name="testOnCreate">false</property>
        </dbInstance>
    </dbGroup>

    <dbGroup name="dbGroup2" rwSplitMode="0" delayThreshold="100" disableHA="true">
        <heartbeat errorRetryCount="1" timeout="10">show slave status</heartbeat>
        <dbInstance name="instanceM2" url="172.18.0.5:3306" user="root" password="123456" maxCon="300" minCon="10"
                    primary="true">
        </dbInstance>
        <dbInstance name="instanceS3" url="172.18.0.6:3306" user="root" password="123456" maxCon="1000" minCon="10" readWeight="2">
            <property name="testOnCreate">false</property>
        </dbInstance>
        <dbInstance name="instanceS4" url="172.18.0.7:3306" user="root" password="123456" maxCon="1000" minCon="10" readWeight="2">
            <property name="testOnCreate">false</property>
        </dbInstance>
    </dbGroup>
</dble:db>

=== actiontech/dble/src/test/resources/route/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE dble:db SYSTEM "db.dtd">
<dble:db xmlns:dble="http://dble.cloud/">

    <dbGroup name="localhost1" rwSplitMode="0">
        <heartbeat>select user()</heartbeat>
        <dbInstance name="hostM1" url="localhost:3306" user="root"
                    password="123456" maxCon="500" minCon="10" primary="true">
        </dbInstance>
    </dbGroup>

    <dbGroup name="localhost2" rwSplitMode="0">
        <heartbeat>select user()</heartbeat>
        <dbInstance name="hostM2" url="localhost:3306" user="root" password="123456" primary="true" maxCon="500"
                    minCon="10">
        </dbInstance>
    </dbGroup>

    <dbGroup name="localhost3" rwSplitMode="0">
        <heartbeat>select user()</heartbeat>
        <dbInstance name="hostM3" url="localhost:3306" user="root" password="123456" maxCon="500" minCon="10"
                    primary="true">
        </dbInstance>
    </dbGroup>

</dble:db>

=== actiontech/dble/src/test/resources/config/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE dble:db SYSTEM "db.dtd">
<dble:db xmlns:dble="http://dble.cloud/">

    <dbGroup name="localhost1" rwSplitMode="0" >
        <heartbeat>select user()</heartbeat>
        <dbInstance name="hostM1" url="localhost:3306" user="root"
                   password="123456" maxCon="500" minCon="10" primary="true">
        </dbInstance>
    </dbGroup>


    <!-- 读权重设置 -->
    <dbGroup name="localhost2" rwSplitMode="0" delayThreshold="100" >
        <heartbeat>select user()</heartbeat>
        <dbInstance name="writeS" url="192.168.1.10:3306" user="root" password="123456" maxCon="1000" minCon="10"  primary="true">
            <!-- can have multi read hosts -->

        </dbInstance>
        <dbInstance name="readS1" url="192.168.1.11:3306" user="root" password="123456" readWeight="1" maxCon="1000" minCon="10" />
        <dbInstance name="readS2" url="192.168.1.12:3306" user="root" password="123456" readWeight="2" maxCon="1000" minCon="10" />
        <dbInstance name="readS3" url="192.168.1.13:3306" user="root" password="123456" readWeight="3" maxCon="1000" minCon="10" />
    </dbGroup>

</dble:db>
