=== actiontech/dble/src/main/resources/sharding.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

        <!--
         -
         - Licensed under the Apache License, Version 2.0 (the "License");
         - you may not use this file except in compliance with the License.
         - You may obtain a copy of the License at
         -
         -      http://www.apache.org/licenses/LICENSE-2.0
         -
         - Unless required by applicable law or agreed to in writing, software
         - distributed under the License is distributed on an "AS IS" BASIS,
         - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         - See the License for the specific language governing permissions and
         - limitations under the License.
        -->
        <!ELEMENT dble:sharding (schema*,shardingNode*,function*)>
        <!ATTLIST dble:sharding xmlns:dble CDATA #FIXED "http://dble.cloud/">
        <!ATTLIST dble:sharding version CDATA #IMPLIED>

        <!ELEMENT schema ((shardingTable*|globalTable*|singleTable*)*)>
        <!ATTLIST schema name NMTOKEN #REQUIRED>
        <!ATTLIST schema shardingNode CDATA #IMPLIED>
        <!ATTLIST schema sqlMaxLimit NMTOKEN #IMPLIED>

        <!ELEMENT shardingTable (childTable*)>
        <!ATTLIST shardingTable name CDATA #REQUIRED>
        <!ATTLIST shardingTable shardingNode CDATA #REQUIRED>
        <!ATTLIST shardingTable shardingColumn NMTOKEN #REQUIRED>
        <!ATTLIST shardingTable function NMTOKEN #REQUIRED>
        <!ATTLIST shardingTable sqlRequiredSharding NMTOKEN #IMPLIED>
        <!ATTLIST shardingTable incrementColumn NMTOKEN #IMPLIED>
        <!ATTLIST shardingTable sqlMaxLimit NMTOKEN #IMPLIED>

        <!ELEMENT globalTable  EMPTY>
        <!ATTLIST globalTable name CDATA #REQUIRED>
        <!ATTLIST globalTable shardingNode CDATA #REQUIRED>
        <!ATTLIST globalTable sqlMaxLimit NMTOKEN #IMPLIED>
        <!ATTLIST globalTable checkClass NMTOKEN #IMPLIED>
        <!ATTLIST globalTable cron CDATA #IMPLIED>

        <!ELEMENT singleTable EMPTY>
        <!ATTLIST singleTable name CDATA #REQUIRED>
        <!ATTLIST singleTable shardingNode CDATA #REQUIRED>
        <!ATTLIST singleTable sqlMaxLimit NMTOKEN #IMPLIED>

        <!ELEMENT childTable (childTable*)>
        <!ATTLIST childTable name NMTOKEN #REQUIRED>
        <!ATTLIST childTable joinColumn NMTOKEN #REQUIRED>
        <!ATTLIST childTable parentColumn NMTOKEN #REQUIRED>
        <!ATTLIST childTable incrementColumn NMTOKEN #IMPLIED>
        <!ATTLIST childTable sqlMaxLimit NMTOKEN #IMPLIED>


        <!ELEMENT shardingNode EMPTY>
        <!ATTLIST shardingNode name CDATA #REQUIRED>
        <!ATTLIST shardingNode dbGroup CDATA #REQUIRED>
        <!ATTLIST shardingNode database CDATA #REQUIRED>

        <!ELEMENT function (property*)>
        <!ATTLIST function name NMTOKEN #REQUIRED>
        <!ATTLIST function class NMTOKEN #REQUIRED>

        <!ELEMENT property (#PCDATA)*>
        <!ATTLIST property name NMTOKEN #REQUIRED>

=== actiontech/dble/src/test/resources/config/sharding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE dble:sharding SYSTEM "sharding.dtd">
<dble:sharding xmlns:dble="http://dble.cloud/">

    <!-- schema定义 -->
    <schema name="dbtest">

        <shardingTable name="tb1" shardingNode="dnTest2,dnTest1" function="func1" shardingColumn="id" />
        <shardingTable name="tb2" shardingNode="dnTest2,dnTest3" function="func1" shardingColumn="id"/>
        <shardingTable name="tb3" shardingNode="dnTest1,dnTest2" function="func1" shardingColumn="id"/>
    </schema>


    <schema name="dbtest2" sqlMaxLimit="100" shardingNode="dnTest4"></schema>

    <schema name="ertest">
        <shardingTable name="er_parent" shardingNode="dnTest1,dnTest2" function="func1" shardingColumn="id">
            <childTable name="er_child1" joinColumn="child1_id" parentColumn="id">
                <childTable name="er_grandson" joinColumn="grandson_id" parentColumn="child1_id"/>
            </childTable>
            <childTable name="er_child2" joinColumn="child2_id" parentColumn="id2"/>
            <childTable name="er_child3" joinColumn="child_char" parentColumn="c_char"/>
            <childTable name="er_child4" joinColumn="child4_id" parentColumn="id2">
                <childTable name="er_grandson2" joinColumn="grandson2_id"
                            parentColumn="child4_id2"/>
            </childTable>
            <childTable name="er_child5" joinColumn="child5_id" parentColumn="id">
                <childTable name="er_grandson3" joinColumn="grandson3_id"
                            parentColumn="child5_id2"/>
            </childTable>
        </shardingTable>
    </schema>
    <!-- 数据节点定义，数据节点由数据源和其他一些参数组织而成。 -->
    <shardingNode name="dnTest1" dbGroup="localhost1" database="db1"/>
    <shardingNode name="dnTest2" dbGroup="localhost1" database="db2"/>
    <shardingNode name="dnTest3" dbGroup="localhost1" database="db3"/>
    <shardingNode name="dnTest4" dbGroup="localhost2" database="db4"/>


    <function name="func1"
              class="com.actiontech.dble.route.function.PartitionByLong">
        <property name="partitionCount">2</property>
        <property name="partitionLength">512</property>
    </function>
</dble:sharding>

=== actiontech/dble/src/main/resources/sharding.xml
<?xml version="1.0"?>
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!DOCTYPE dble:sharding SYSTEM "sharding.dtd">
<dble:sharding xmlns:dble="http://dble.cloud/" version="3.0">
	<schema name="schema1" sqlMaxLimit="100"  shardingNode="dn5">
		<shardingTable name="test1" shardingNode="dn1,dn2,dn3,dn4" function="func_mod" shardingColumn="id" sqlMaxLimit="200" />
		<shardingTable name="test_table" shardingNode="dn1,dn2,dn3,dn4"  function="func_mod" shardingColumn="id" />
		<shardingTable name="sharding_two_node" shardingNode="dn1,dn2" function="two-long" shardingColumn="id"/>
		<shardingTable name="sharding_two_node2" shardingNode="dn1,dn2" function="two-long" shardingColumn="id"/>
		<shardingTable name="sharding_2_t1" shardingNode="dn1,dn2" function="two-long" shardingColumn="id"/>
		<shardingTable name="sharding_4_t1" shardingNode="dn1,dn2,dn3,dn4"  function="func_mod" shardingColumn="id" /></schema>
	<schema name="schema2" sqlMaxLimit="100" shardingNode="dn5">
		<shardingTable name="sharding_2_t2" shardingNode="dn1,dn2" function="two-long" shardingColumn="id"/>
		<shardingTable name="sharding_4_t2" shardingNode="dn1,dn2,dn3,dn4"  function="func_mod" shardingColumn="id" />
	</schema>
	<schema name="schema3" sqlMaxLimit="100" shardingNode="dn5">
	</schema>
	<schema name="testdb" shardingNode="dn1">
		<shardingTable name="sharding_2_t1" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id"/>
		<shardingTable name="sharding_two_node" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id"/>
		<shardingTable name="sharding_4_t1" shardingNode="dn1,dn2,dn3,dn4" function="func_mod" shardingColumn="id" />

		<singleTable name="table_c" shardingNode="dn1" />
		<globalTable name="tb_global1" shardingNode="dn1,dn3"/>
		<shardingTable name="tb_parent" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id">
			<childTable name="tb_child1" joinColumn="child1_id" parentColumn="id">
				<childTable name="tb_grandson1" joinColumn="grandson1_id" parentColumn="child1_id"/>
				<childTable name="tb_grandson2" joinColumn="grandson2_id" parentColumn="child1_id2"/>
			</childTable>
			<childTable name="tb_child2" joinColumn="child2_id" parentColumn="id"/>
			<childTable name="tb_child3" joinColumn="child3_id" parentColumn="id2"/>
		</shardingTable>



	</schema>


	<schema name="testdb2">
		<shardingTable name="sharding_4_t2" shardingNode="dn1,dn2,dn3,dn4" function="func_mod" shardingColumn="id" />
		<globalTable name="global_4_t1" shardingNode="dn1,dn2,dn3,dn4"/>
	</schema>


	<schema name="ermdb" shardingNode="ermdn1"></schema>

	<shardingNode name="ermdn1" dbGroup="dbGroup1" database="erm" />
	<!-- <dataNode name="dn1$0-743" dbGroup="dbGroup1" database="db$0-743" /> -->
	<shardingNode name="dn1" dbGroup="dbGroup1" database="db_1"/>
	<shardingNode name="dn2" dbGroup="dbGroup2" database="db_2"/>
	<shardingNode name="dn3" dbGroup="dbGroup1" database="db_3"/>
	<shardingNode name="dn4" dbGroup="dbGroup2" database="db_4"/>
	<shardingNode name="dn5" dbGroup="dbGroup1" database="db_5"/>
	<shardingNode name="C3_00$0-9" dbGroup="dbGroup1" database="C3_00$0-9"/>
	<shardingNode name="C3_0$10-63" dbGroup="dbGroup1" database="C3_0$10-63"/>
	<!--&lt;!&ndash;<shardingNode name="dn6" dbGroup="dbGroup2" database="db_6"/>&ndash;&gt;-->
	<!--&lt;!&ndash;<shardingNode name="dn7" dbGroup="dbGroup2" database="db_7"/>&ndash;&gt;-->
	<!--<shardingNode name="dn8" dbGroup="dbGroup1" database="yhq_test"/>-->
	<!--<shardingNode name="dn9" dbGroup="dbGroup3" database="yhq_test"/>-->

	<function class="Hash" name="two-long">
		<property name="partitionCount">2</property>
		<property name="partitionLength">1</property>
	</function>
	<function name="rule_simple" class="Hash">
		<property name="partitionCount">4</property>
		<property name="partitionLength">1</property>
	</function>


	<!-- Hash partition,when partitionLength=1, it is a mod partition-->
	<!--MAX(sum(count*length[i]) must not more then 2880-->
	<function name="func_common_hash" class="Hash">
		<property name="partitionCount">2</property>
		<property name="partitionLength">512</property>
	</function>
	<!-- Hash partition,when partitionLength=1, it is a mod partition-->
	<!--MAX(sum(count*length[i]) must not more then 2880-->
	<function name="func_uneven_hash" class="Hash">
		<property name="partitionCount">2,1</property>
		<property name="partitionLength">256,512</property>
	</function>
	<!-- eg:  mod 4 -->
	<function name="func_mod64" class="Hash">
		<property name="partitionCount">64</property>
		<property name="partitionLength">1</property>
	</function>
	<!-- eg:  mod 4 -->
	<function name="func_mod" class="Hash">
		<property name="partitionCount">4</property>
		<property name="partitionLength">1</property>
	</function>


	<function name="func_test" class="Hash">
		<property name="partitionCount">2,3</property>
		<property name="partitionLength">10,5</property>
	</function>
	<!-- jumpStringHash partition for string-->
	<function name="func_jumpHash" class="jumpStringHash">
		<property name="partitionCount">2</property>
		<property name="hashSlice">0:2</property>
	</function>

	<!-- Hash partition for string-->
	<function name="func_hashString" class="StringHash">
		<property name="partitionCount">4</property>
		<property name="partitionLength">256</property>
		<property name="hashSlice">0:2</property>
		<!--<property name="hashSlice">-4:0</property> -->
	</function>

	<!-- date partition -->
	<!-- 4 case:
    1.set sEndDate and defaultNode: input <sBeginDate ,router to defaultNode; input>sEndDate ,mod the period
    2.set sEndDate, but no defaultNode:input <sBeginDate report error; input>sEndDate ,mod the period
    3.set defaultNode without sEndDate: input <sBeginDate router to defaultNode;input>sBeginDate + (node size)*sPartionDay-1 will report error(expected is defaultNode,but can't control now)
    4.sEndDate and defaultNode are all not set: input <sBeginDate report error;input>sBeginDate + (node size)*sPartionDay-1 will report error
     -->
	<function name="func_date" class="Date">
		<property name="dateFormat">yyyy-MM-dd</property>
		<property name="sBeginDate">2015-01-01</property>
		<property name="sEndDate">2015-01-31 </property> <!--if not set sEndDate,then in fact ,the sEndDate = sBeginDate+ (node size)*sPartionDay-1 -->
		<property name="sPartionDay">10</property>
		<property name="defaultNode">0</property><!--the default is -1-->
	</function>

	<!-- pattern partition -->
	<!--mapFile must contains all value of 0~patternValue-1,key and value must be Continuous increase-->
	<function name="func_pattern" class="PatternRange">
		<property name="mapFile">partition-pattern.txt</property>
		<property name="patternValue">1024</property>
		<property name="defaultNode">0</property><!--contains string which is not number,router to default node-->
	</function>
</dble:sharding>

=== actiontech/dble/src/test/resources/sharding.xml
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!DOCTYPE dble:sharding SYSTEM "sharding.dtd">
<dble:sharding xmlns:dble="http://dble.cloud/" version="3.0">
    <schema name="cndb" >
        <shardingTable name="offer" shardingNode="offer_dn$0-127" function="func" shardingColumn="member_id"/>
        <shardingTable name="offer_detail" shardingNode="detail_dn0,detail_dn$1-127" function="func2" shardingColumn="offer_id" sqlRequiredSharding="false"/>
        <shardingTable name="offer_date" shardingNode="detail_dn0,detail_dn$1-127" function="by-date" shardingColumn="col_date" sqlRequiredSharding="false"/>
        <globalTable name="independent"  shardingNode="independent_dn$0-126,independent_dn127"/>
    </schema>

    <schema name="dbtest">
        <shardingTable name="tb2" shardingNode="dnTest2,dnTest3" function="func0" shardingColumn="id"/>
    </schema>

    <schema name="dubbo" shardingNode="dubbo_dn"/>

    <schema name="dubbo2" shardingNode="dn1">
        <globalTable name="company"  shardingNode="dn1,dn2,dn3"/>
        <globalTable name="goods"  shardingNode="dn1,dn2,dn3"/>
    </schema>

    <schema name="ignoreSchemaTest" shardingNode="cndb_dn" />

    <schema name="config">
        <shardingTable name="offer" shardingNode="offer_dn$0-127" function="func" shardingColumn="member_id" sqlRequiredSharding="true"/>
    </schema>

    <schema name="none_node_test">
        <shardingTable name="offer" shardingNode="offer_dn$0-127" function="func" shardingColumn="member_id" sqlRequiredSharding="true"/>
    </schema>

    <schema name="solo1" shardingNode="solo1"/>

    <schema name="TESTDB" sqlMaxLimit="100">
        <shardingTable name="travelrecord" shardingNode="dn1,dn2,dn3" function="rang-long" shardingColumn="id"/>
        <!-- global table is auto cloned to all defined data nodes ,so can join
            with any table whose sharding node is in the same data node -->
        <globalTable name="company"  shardingNode="dn1,dn2,dn3"/>
        <globalTable name="goods"  shardingNode="dn1,dn2,dn3"/>
        <singleTable name="notpartionTable" shardingNode="dn1"/>
        <globalTable name="area"  shardingNode="dn1,dn2,dn3"/>
        <shardingTable name="employee" shardingNode="dn1,dn2" function="func1" shardingColumn="sharding_id"/>
        <shardingTable name="customer" shardingNode="dn1,dn2" function="rang-long2" shardingColumn="id">
            <childTable name="orders" joinColumn="customer_id" parentColumn="id">
                <childTable name="order_items" joinColumn="order_id" parentColumn="id"/>
            </childTable>
            <childTable name="customer_addr" joinColumn="customer_id" parentColumn="id"/>
        </shardingTable>
        <singleTable name="globalsn"  shardingNode="dn1"/>
    </schema>

    <schema name="mysqldb" sqlMaxLimit="100">
        <shardingTable name="autoslot" shardingNode="dn1,dn2" function="rang-long2" shardingColumn="id"/>
        <shardingTable name="offer" shardingNode="dn1,dn2" function="rang-long2" shardingColumn="id"/>
        <singleTable name="offer1" shardingNode="dn1"/>
    </schema>


    <shardingNode name="dn1" dbGroup="localhost1" database="db1"/>
    <shardingNode name="dn2" dbGroup="localhost1" database="db2"/>
    <shardingNode name="dn3" dbGroup="localhost1" database="db3"/>
    <shardingNode name="cndb_dn" dbGroup="localhost1" database="db4"/>
    <shardingNode name="offer_dn$0-127" dbGroup="localhost1" database="db1$0-127"/>
    <shardingNode name="detail_dn$0-127" dbGroup="localhost1" database="db2$0-127"/>
    <shardingNode name="test_wild1$1-3" dbGroup="localhost$1-3" database="dbx"/>
    <shardingNode name="test_wild$1-6" dbGroup="localhost$1-3" database="db3$1-2"/>
    <shardingNode name="independent_dn$0-127" dbGroup="localhost1" database="db7_$0-127"/>
    <shardingNode name="dubbo_dn" dbGroup="localhost1" database="db8"/>
    <shardingNode name="solo1" dbGroup="localhost1" database="db9"/>

    <!-- 数据节点定义，数据节点由数据源和其他一些参数组织而成。 -->
    <shardingNode name="dnTest1" dbGroup="localhost4" database="db1"/>
    <shardingNode name="dnTest2" dbGroup="localhost4" database="db2"/>
    <shardingNode name="dnTest3" dbGroup="localhost4" database="db3"/>
    <!-- 路由函数定义 -->
    <function name="func0" class="com.actiontech.dble.route.function.PartitionByLong">
        <property name="partitionCount">2</property>
        <property name="partitionLength">512</property>
    </function>


    <function name="func1"
              class="com.actiontech.dble.route.function.PartitionByFileMap">
        <property name="defaultNode">0</property>
        <property name="mapFile">sharding.txt</property>
    </function>
    <function name="func"
              class="com.actiontech.dble.route.function.PartitionByString">
        <property name="partitionCount">128</property>
        <property name="partitionLength">8</property>
        <property name="hashSlice">:8</property>
    </function>
    <function name="func2" class="com.actiontech.dble.route.function.PartitionByLong">
        <property name="partitionCount">128</property>
        <property name="partitionLength">8</property>
    </function>
    <function name="rang-long"
              class="com.actiontech.dble.route.function.AutoPartitionByLong">
        <property name="mapFile">autopartition-long.txt</property>
    </function>
    <function name="rang-long2"
              class="com.actiontech.dble.route.function.AutoPartitionByLong">
        <property name="mapFile">autopartition-long2.txt</property>
    </function>
    <function name="by-date"
              class="com.actiontech.dble.route.function.PartitionByDate">
        <property name="sBeginDate">2014-01-01</property>
        <property name="sPartionDay">10</property>
        <property name="dateFormat">yyyy-MM-dd</property>
    </function>
</dble:sharding>

=== actiontech/dble/src/main/resources/sharding_template.xml
<?xml version="1.0"?>
<!--
  ~ Copyright (C) 2016-2020 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!DOCTYPE dble:sharding SYSTEM "sharding.dtd">
<dble:sharding xmlns:dble="http://dble.cloud/" version="3.0">

    <schema name="testdb"  sqlMaxLimit="100">
        <shardingTable name="tb_enum_sharding" shardingNode="dn1,dn2" sqlMaxLimit="200" function="func_enum" shardingColumn="code"/>
        <shardingTable name="tb_range_sharding" shardingNode="dn1,dn2,dn3" function="func_range" shardingColumn="id"/>
        <!--er tables-->
        <shardingTable name="tb_hash_sharding" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id"/>
        <shardingTable name="tb_hash_sharding_er1" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id"/>
        <shardingTable name="tb_hash_sharding_er2" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id2"/>
        <shardingTable name="tb_hash_sharding_er3" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id" incrementColumn="id2"/>

        <shardingTable name="tb_uneven_hash" shardingNode="dn1,dn2,dn3" function="func_uneven_hash" shardingColumn="id"/>

        <shardingTable name="tb_mod" shardingNode="dn1,dn2,dn3,dn4" function="func_mod" shardingColumn="id" sqlRequiredSharding="true"/>

        <shardingTable name="tb_jump_hash" shardingNode="dn1,dn2" function="func_jumpHash" shardingColumn="code"/>

        <shardingTable name="tb_hash_string" shardingNode="dn1,dn2,dn3,dn4" function="func_hashString" shardingColumn="code"/>

        <shardingTable name="tb_date" shardingNode="dn1,dn2,dn3,dn4" function="func_date" shardingColumn="create_date"/>

        <shardingTable name="tb_pattern" shardingNode="dn1,dn2" function="func_pattern" shardingColumn="id"/>
        <!--global  tables-->
        <globalTable name="tb_global1" shardingNode="dn1,dn2" sqlMaxLimit="103" />
        <globalTable name="tb_global2" shardingNode="dn1,dn2,dn3,dn4" cron="0 0 0 * * ?" checkClass="CHECKSUM"/>
        <!--single node table-->
        <singleTable name="tb_single" shardingNode="dn6" sqlMaxLimit="105"/>
        <!--er tables-->
        <shardingTable name="tb_parent" shardingNode="dn1,dn2" function="func_common_hash" shardingColumn="id">
            <childTable name="tb_child1" joinColumn="child1_id" parentColumn="id" sqlMaxLimit="201">
                <childTable name="tb_grandson1" joinColumn="grandson1_id" parentColumn="child1_id"/>
                <childTable name="tb_grandson2" joinColumn="grandson2_id" parentColumn="child1_id2"/>
            </childTable>
            <childTable name="tb_child2" joinColumn="child2_id" parentColumn="id"/>
            <childTable name="tb_child3" joinColumn="child3_id" parentColumn="id2"/>
        </shardingTable>
    </schema>
    <!-- sharding testdb2 route to database named dn5 in localhost2  -->
    <schema name="testdb2" shardingNode="dn5"/>
    <shardingNode name="dn1" dbGroup="dbGroup1" database="db_1"/>
    <shardingNode name="dn2" dbGroup="dbGroup2" database="db_2"/>
    <shardingNode name="dn3" dbGroup="dbGroup1" database="db_3"/>
    <shardingNode name="dn4" dbGroup="dbGroup2" database="db_4"/>
    <shardingNode name="dn5" dbGroup="dbGroup1" database="db_5"/>
    <shardingNode name="dn6" dbGroup="dbGroup2" database="db_6"/>
    <!-- enum partition -->
    <function name="func_enum" class="Enum">
        <property name="mapFile">partition-enum.txt</property>
        <property name="defaultNode">0</property><!--the default is -1,means unexpected value will report error-->
        <property name="type">0</property><!--0 means key is a number, 1 means key is a string-->
    </function>
    <!-- number range partition -->
    <function name="func_range" class="NumberRange">
        <property name="mapFile">partition-number-range.txt</property>
        <property name="defaultNode">0</property><!--he default is -1,means unexpected value will report error-->
    </function>
    <!-- Hash partition,when partitionLength=1, it is a mod partition, MAX(sum(count*length[i]) must not more then 2880-->
    <function name="func_common_hash" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">512</property>
    </function>
    <!-- Hash partition,when partitionLength=1, it is a mod partition, MAX(sum(count*length[i]) must not more then 2880-->
    <function name="func_uneven_hash" class="Hash">
        <property name="partitionCount">2,1</property>
        <property name="partitionLength">256,512</property>
    </function>
    <!-- eg:  mod 4 -->
    <function name="func_mod" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>
    <!-- jumpStringHash partition for string-->
    <function name="func_jumpHash" class="jumpStringHash">
        <property name="partitionCount">2</property>
        <property name="hashSlice">0:2</property>
    </function>
    <!-- Hash partition for string-->
    <function name="func_hashString" class="StringHash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">256</property>
        <property name="hashSlice">0:2</property>
        <!--<property name="hashSlice">-4:0</property> -->
    </function>
    <!-- date partition  4 case:
    1.set sEndDate and defaultNode: input <sBeginDate ,router to defaultNode; input>sEndDate ,mod the period
    2.set sEndDate, but no defaultNode:input <sBeginDate report error; input>sEndDate ,mod the period
    3.set defaultNode without sEndDate: input <sBeginDate router to defaultNode;input>sBeginDate + (node size)*sPartionDay-1 will report error(expected is defaultNode,but can't control now)
    4.sEndDate and defaultNode are all not set: input <sBeginDate report error;input>sBeginDate + (node size)*sPartionDay-1 will report error
     -->
    <function name="func_date" class="Date">
        <property name="dateFormat">yyyy-MM-dd</property>
        <property name="sBeginDate">2015-01-01</property>
        <property name="sEndDate">2015-01-31</property> <!--if not set sEndDate,then in fact ,the sEndDate = sBeginDate+ (node size)*sPartionDay-1 -->
        <property name="sPartionDay">10</property>
        <property name="defaultNode">0</property><!--the default is -1-->
    </function>
    <!-- pattern partition : mapFile must contains all value of 0~patternValue-1,key and value must be Continuous increase-->
    <function name="func_pattern" class="PatternRange">
        <property name="mapFile">partition-pattern.txt</property>
        <property name="patternValue">1024</property>
        <property name="defaultNode">0</property><!--contains string which is not number,router to default node-->
    </function>
</dble:sharding>
